export async function getAllProducts() {
  const promise = new Promise((res) => setTimeout(() => res(PRODUCTS), 1500))
  return await promise
}

export async function getProductById(id) {
  const a = parseFloat(id)
  const promise = new Promise((res) => {
    setTimeout(() => res(PRODUCTS.find((x) => x.id === parseFloat(id))), 1500)
  })
  return await promise
}

export const PRODUCTS = [
  {
    id: 1,
    title: "Балкон кутовий",
    image: "/images/products/DBBalkon1.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    id: 2,
    title: " Балкон трапеція",
    image: "/images/products/DBBalkon2.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 128.0,
    // discontProc: 30,
  },
  {
    id: 3,
    title: "Балкон дуговий",
    image: "/images/products/DBBalkon3.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 120.0,
    // discontProc: 0,
  },
  {
    id: 4,
    title: "Сходи",
    image: "/images/products/DBShoduZov.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 30,
  },
  {
    id: 5,
    title: "Сходи квадрат",
    image: "/images/products/DBShoduKv.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 30,
  },
  {
    id: 6,
    title: "Сходи",
    image: "/images/products/DBShodu.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    discontProc: 0,
  },
  {
    id: 7,
    title: "Сходи",
    image: "/images/products/DBShoduVn.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    id: 8,
    title: "Сходи",
    image: "/images/products/DBShoduVn1.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    id: 20,
    title: "Сходи",
    image: "/images/products/DBShoduZov.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    id: 9,
    title: "Тераса",
    image: "/images/products/DBTerasa1.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 30,
  },
  {
    id: 10,
    title: "Тераса",
    image: "/images/products/DBTerasa2.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 30,
  },

  {
    id: 11,
    title: "Веранда внутрішня",
    image: "/images/products/DBVerandaVn.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    id: 12,
    title: "Опора під виноград",
    image: "/images/products/BDVunograd.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    id: 13,
    title: "Ворота",
    image: "/images/products/DBVorota3.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    id: 14,
    title: "Ворота",
    image: "/images/products/DBVorota1.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    id: 15,
    title: "Решітка на вікно",
    image: "/images/products/DBVikno.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    discontProc: 0,
  },
  {
    id: 16,
    title: "Лавка",
    image: "/images/products/DBLavka.jpg",
    description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    id: 17,
    title: "Паркан",
    image: "/images/products/DBParkan.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    id: 18,
    title: "Паркан",
    image: "/images/products/DBParkan1.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    discontProc: 0,
  },
  {
    id: 19,
    title: "Паркан",
    image: "/images/products/DBParkan2.jpg",
    description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },

  {
    id: 21,
    title: "Рушникосушка-квадратна труба",
    image: "/images/products/DBSushilka.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    id: 22,
    title: "Рушникосушка-квадратна труба",
    image: "/images/products/DBSushilka1.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    id: 23,
    title: "Рушникосушка-квадратна труба",
    image: "/images/products/DBSushilka2.jpg",
    // description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
  {
    id: 26,
    title: "Балкон плюс навіс",
    image: "/images/products/DBBalkonNavis.jpg",
    description: "Виготовлений з труб @20. і 15. Опуклі в зовнішню сторону. ВІдшліфовані.",
    // price: 20.0,
    // discontProc: 0,
  },
]
