// import Header from "@/components/Header"
import "./globals.css"
import { Inter } from "next/font/google"
import Header from "../components/header/Header"
import HeaderTape from "../components/header/HeaderTape"


const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    // <html lang="en" class="dark">
    <html lang="en" class="light">
      <body className={inter.className}>
        {/* <HeaderTape /> */}
        <Header />
        <main className=" dark:bg-slate-800 min-h-screen max-w-7xl mx-auto px- xl:px-0 mt-28">
          {children}
        </main>
      </body>
    </html>
  )
}
