// import Header from "@/components/Header"
import Header from "../components/Header"
import "./globals.css"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="min-h-screen max-w-7xl mx-auto px- xl:px-0 mt-28">{children}</main>
      </body>
    </html>
  )
}
